CREATE DATABASE Clinica;
GO

USE Clinica;
GO

CREATE TABLE Clinica(
IdClinica INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
Endereco VARCHAR(100) NOT NULL,
);
GO

CREATE TABLE Pet(
IdNome INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(50) NOT NULL,
Nascimento DATE NOT NULL,
);
GO

CREATE TABLE TipoPet(
IdTipoPet INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(50) NOT NULL,
IdNome INT FOREIGN KEY REFERENCES Pet(IdNome),
);
GO

CREATE TABLE Raca(
IdRaca INT PRIMARY KEY IDENTITY NOT NULL,
Descricao VARCHAR(50) NOT NULL,
IdNome INT FOREIGN KEY REFERENCES Pet(IdNome) NOT NULL,
);
GO

CREATE TABLE Dono(
IdDono INT PRIMARY KEY IDENTITY NOT NULL,
Dono VARCHAR(100) NOT NULL,
IdNome INT FOREIGN KEY REFERENCES Pet(IdNome) NOT NULL,
);
GO

CREATE TABLE Veteninario(
IdVeteninario INT PRIMARY KEY IDENTITY NOT NULL,
Nome VARCHAR(100) NOT NULL,
IdNome INT FOREIGN KEY REFERENCES Pet(IdNome) NOT NULL,
);
GO



